version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: voicebot_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_DATABASE: voicebot_db
      MYSQL_USER: voicebot_user
      MYSQL_PASSWORD: Aa123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: voicebot_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Aa123456
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
